### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by sc610889477** [shuyabin/caidao#1]
main.go:4:2: cannot find package "caidao/models" in any of:
	/usr/local/Cellar/go/1.11/libexec/src/caidao/models (from $GOROOT)
	/Users/username/go/src/caidao/models (from $GOPATH)
main.go:5:2: cannot find package "caidao/routers" in any of:
	/usr/local/Cellar/go/1.11/libexec/src/caidao/routers (from $GOROOT)
	/Users/username/go/src/caidao/routers (from $GOPATH)

**Comment by sc610889477** [comment]
我把菜刀复制了一份到环境变量路径，然后启动成功了。。。

**Comment by shuyabin** [comment]
哇哈哈..恭喜恭喜
